# Generated by Django 3.1.2 on 2021-10-20 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Select', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatement',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
